services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: icon-app
    restart: unless-stopped

    working_dir: /var/www

    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      ASSET_URL: ${ASSET_URL}
      APP_KEY: ${APP_KEY}

      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    volumes:
      - icon_storage:/var/www/storage

    networks:
      - icon_network


  icon:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile

    container_name: icon-nginx
    restart: unless-stopped

    depends_on:
      - app

    volumes:
      - icon_storage:/var/www/storage:ro

    networks:
      - icon_network
      - caddy_network


  mysql:
    image: mysql:8.4

    container_name: icon-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - icon_mysql_data:/var/lib/mysql

    networks:
      - icon_network


volumes:

  icon_mysql_data:
  icon_storage:


networks:

  icon_network:

  caddy_network:
    external: true
    name: caddy_caddy_network